import pytest
from utilities.BaseClass import BaseClass
from selenium.webdriver import Keys
from selenium.webdriver.common.by import By
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver import ActionChains
import autoit
import time
class TestClass(BaseClass):
    def test_demo1(self):

        username = "murugan1@gmail.com"
        phoneno = "8764523189"
        password = "OhR@1234"
        Qsubject = "Dental"
        PG = "MD"
        action = ActionChains(self.driver)
        time.sleep(3)
        self.driver.find_element(By.NAME, 'register-now').click()
        time.sleep(3)
        self.driver.find_element(By.XPATH, "//input[@name ='email']").send_keys(username)
        element = self.driver.find_element(By.XPATH, "//button[@class = 'btn rounded-0 pl-5 pr-5 btn-primary']")
        self.driver.execute_script("arguments[0].click();", element)
        time.sleep(3)
        self.driver.find_element(By.XPATH, "//label[@class ='p-2 text-primary font-weight-bold']").click()
        time.sleep(3)
        autoit.control_focus("Open", "Edit1")
        time.sleep(3)
        autoit.control_set_text("Open", "Edit1", "C:\\Users\\ALAGU SUNDARI\\OneDrive\\Desktop\\image4.jpg")
        time.sleep(3)
        autoit.control_click("Open", "Button1")
        WebDriverWait(self.driver, 10).until(EC.element_to_be_clickable((By.XPATH,
                                                                    "//div[@class ='border-top d-flex py-3 mx-3']/div[@class ='d-flex']/button[@name='crop-image']"))).click()
        WebDriverWait(self.driver, 10).until(EC.element_to_be_clickable((By.XPATH,
                                                                    "//div[@class ='border-top d-flex py-3 mx-3']/div[@class ='d-flex']/button[@name='crop-image-apply']"))).click()
        WebDriverWait(self.driver, 10).until(EC.element_to_be_clickable((By.XPATH, "//div[@name='title_id'] "))).click()
        time.sleep(3)
        self.driver.find_element(By.XPATH, "//li[@id ='vs1__option-0']").click()
        self.driver.find_element(By.XPATH, "//input[@name = 'first_name']").send_keys("Arun")
        self.driver.find_element(By.XPATH, "//input[@name = 'middle_name']").send_keys("Pradesh")
        self.driver.find_element(By.XPATH, "//input[@name = 'surname']").send_keys("E")
        self.driver.find_element(By.XPATH, "//div[@name ='date-dropdown-date-dob']").click()
        self.driver.find_element(By.XPATH, "//li[@id = 'vs2__option-28']").click()
        self.driver.find_element(By.XPATH, "//div[@name  = 'date-dropdown-month-dob']").click()
        self.driver.find_element(By.XPATH, "//li[@id =  'vs3__option-11']").click()
        self.driver.find_element(By.XPATH, " //div[@name = 'date-dropdown-year-dob']").click()
        Year = self.driver.find_element(By.XPATH, "//li[@id =  'vs4__option-44']").click()
        self.driver.find_element(By.XPATH, "//div[@name = 'gender']").click()
        self.driver.find_element(By.XPATH, "//li[@id ='vs5__option-0']").click()
        time.sleep(3)
        self.driver.find_element(By.XPATH, " //div[@name = 'nationality']").click()
        self.driver.find_element(By.XPATH, "//li[@id = 'vs6__option-8']").click()
        self.driver.find_element(By.XPATH, " //div[@name ='country_id']").click()
        self.driver.find_element(By.XPATH, "//li[@id = 'vs7__option-12']").click()
        time.sleep(3)
        self.driver.find_element(By.XPATH, "//div[@name='phone-code-phone']").click()
        self.driver.find_element(By.XPATH, "//li[@id = 'vs8__option-49']").click()
        self.driver.find_element(By.XPATH, "//input[@name='phone-number-phone']").send_keys(phoneno)
        time.sleep(3)
        contact = self.driver.find_element(By.XPATH, "//div[@name ='contact-information']")
        self.driver.execute_script("arguments[0].scrollIntoView();", contact)
        time.sleep(3)
        slide = self.driver.find_element(By.XPATH, "//input[@name ='isRegisteredWhatsapp'] ")
        action.move_to_element(slide).click().perform()

        time.sleep(3)
        self.driver.find_element(By.XPATH, "(//div[@name ='preferred_contact_method'])[1]").click()
        self.driver.find_element(By.XPATH, "//li[@id = 'vs9__option-3']").click()
        self.driver.find_element(By.XPATH, "//input[@name = 'alternate_email']").send_keys(username)
        prof = self.driver.find_element(By.XPATH, "//div[@name ='candidate_type']")
        self.driver.execute_script("arguments[0].scrollIntoView();", prof)
        self.driver.find_element(By.XPATH, "//div[@name ='candidate_type']").click()
        self.driver.find_element(By.XPATH, "//li[@id = 'vs10__option-3']").click()
        self.driver.find_element(By.XPATH, "//div[@name ='main_qualification_country_id'] ").click()
        self.driver.find_element(By.XPATH, " //li[@id = 'vs11__option-3']").click()
        Qname = self.driver.find_element(By.XPATH, "//label[text() = 'Qualification Name']")
        self.driver.execute_script("arguments[0].scrollIntoView();", Qname)
        time.sleep(3)
        self.driver.find_element(By.XPATH, "//div[@name ='main_qualification_id']").click()
        self.driver.find_element(By.XPATH, "//li[@id = 'vs12__option-8']").click()
        self.driver.find_element(By.XPATH, "//input[@name = 'main_qualification_description'] ").send_keys(Qsubject)
        Mony = self.driver.find_element(By.XPATH, "//div[@name= 'month-and-year-awarded']")
        self.driver.execute_script("arguments[0].scrollIntoView();", Mony)
        self.driver.find_element(By.XPATH, "//div[@name= 'date-dropdown-month-qualified_date']").click()
        self.driver.find_element(By.XPATH, "//li[@id ='vs13__option-10']").click()
        self.driver.find_element(By.XPATH, "//div[@name= 'date-dropdown-year-qualified_date']").click()
        self.driver.find_element(By.XPATH, "//li[@id = 'vs14__option-28']").click()
        self.driver.find_element(By.XPATH, " //div[@name= 'speciality_id']").click()
        self.driver.find_element(By.XPATH, "//li[@id = 'vs15__option-6']").click()
        Reg = self.driver.find_element(By.XPATH, "//div[@name= 'registration-details']")
        self.driver.execute_script("arguments[0].scrollIntoView();", Reg)
        self.driver.find_element(By.XPATH, "//input[@name ='password']").send_keys(password)
        self.driver.find_element(By.XPATH, "//input[@name ='confirmPassword']").send_keys(password)
        Upload = self.driver.find_element(By.XPATH, "//h5[ @class= 'text-primary']")
        self.driver.execute_script("arguments[0].scrollIntoView();", Upload)
        self.driver.find_element(By.XPATH, "//div[@name ='document_type']").click()
        self.driver.find_element(By.XPATH, "//li[@id = 'vs16__option-0']").click()
        self.driver.find_element(By.XPATH, "//input[@class ='mr-2']").click()
        self.driver.find_element(By.XPATH, "//div[@name ='upload-document']//div").click()
        time.sleep(3)
        autoit.control_focus("Open", "Edit1")
        time.sleep(3)
        autoit.control_set_text("Open", "Edit1", "C:\\Users\\ALAGU SUNDARI\\OneDrive\\Desktop\\sundari.docx")
        time.sleep(3)
        autoit.control_click("Open", "Button1")
        submit = self.driver.find_element(By.XPATH, "//div[@class ='row']//button[@name = 'registration-submit']")
        self.driver.execute_script("arguments[0].click();", submit)
        time.sleep(3)
class TestClass1(BaseClass):
    def test_demo2(self):
        time.sleep(4)
        username = "murugan1@gmail.com"
        password = "OhR@1234"
        action = ActionChains(self.driver)
        self.driver.find_element(By.NAME, 'login-email').send_keys(username)
        self.driver.find_element(By.NAME, 'login-password').send_keys(password)
        self.driver.find_element(By.XPATH, "//button[@name ='login-submit']").click()
        time.sleep(4)
        self.driver.find_element(By.LINK_TEXT, 'View Profile').click()
        time.sleep(3)
        Edit = self.driver.find_element(By.XPATH, "//div/button[@title ='Edit Profile']")
        self.driver.execute_script("arguments[0].click();", Edit)
        time.sleep(3)
        job = self.driver.find_element(By.XPATH, "//div/div/input[@name ='current_job']")
        job.clear()
        job.send_keys("senior")
        time.sleep(3)
        self.driver.find_element(By.XPATH, "(//div/button[@class ='hand-icon action-button'])[1]").click()
        time.sleep(2)
        add = self.driver.find_element(By.XPATH, "//button[@class = 'btn btn-primary small mr-2']")
        self.driver.execute_script("arguments[0].click();", add)
        move = self.driver.find_element(By.XPATH, "//label[@name ='lbl_main_qualification_year']")
        self.driver.execute_script("arguments[0].scrollIntoView();", move)
        time.sleep(2)
        self.driver.find_element(By.XPATH, "//div[@name ='country_id']").click()
        self.driver.find_element(By.XPATH, "//li[@id ='vs6__option-0']").click()
        time.sleep(3)
        self.driver.find_element(By.XPATH, "//div[@name ='main_qualification_id']").click()
        self.driver.find_element(By.XPATH, "//li[@id = 'vs7__option-4']").click()
        Qyear = self.driver.find_element(By.XPATH, "//label[@name  ='lbl_main_qualification_year']")
        self.driver.execute_script("arguments[0].scrollIntoView();", Qyear)
        self.driver.find_element(By.XPATH, "//div[@name ='date-dropdown-month-qualified_date']").click()
        self.driver.find_element(By.XPATH, "//li[@id = 'vs8__option-11']").click()
        self.driver.find_element(By.XPATH, "//div[@name ='date-dropdown-year-qualified_date']").click()
        self.driver.find_element(By.XPATH, "//li[@id ='vs9__option-37']").click()
        time.sleep(3)
        ele = self.driver.find_element(By.XPATH, "//div[@class ='vue-slider vue-slider-ltr']")
        action.drag_and_drop_by_offset(ele, 60, 0).perform()
        self.driver.find_element(By.XPATH, "//div[@name ='issued_by']").click()
        self.driver.find_element(By.XPATH, "//li[@id ='vs10__option-0']").click()
        self.driver.find_element(By.XPATH, "//button[@class ='btn icon icon-edit mb-2']").click()
        self.driver.find_element(By.XPATH, "//button[@class ='btn icon']").click()
        self.driver.find_element(By.XPATH, "(//footer/div/span/button[@class ='btn ml-2 btn-danger'])[1]").click()
        self.driver.implicitly_wait(10)
        self.driver.find_element(By.XPATH, "//a[@class ='data text-primary'] ").click()
        self.driver.implicitly_wait(10)
        self.driver.find_element(By.XPATH,"//div[@class = 'modal-content']/footer/button[@class ='btn px-4 btn-primary'] ").click()
        self.driver.implicitly_wait(10)
        self.driver.find_element(By.XPATH,"//div[@class ='col-md-4']/div/button[@class ='btn btn-primary small mr-2']").click()
        self.driver.implicitly_wait(10)
        self.driver.find_element(By.XPATH,"(//button[@class ='hand-icon action-button']/*[local-name()='svg'])[2]").click()
        special = self.driver.find_element(By.XPATH, "//div[@class = 'candidate-profile specialization']")
        self.driver.execute_script("arguments[0].scrollIntoView();", special)
        self.driver.find_element(By.XPATH, "//div[@name ='speciality_id']").click()
        self.driver.find_element(By.XPATH, "//li[@id = 'vs4__option-7']").click()
        self.driver.implicitly_wait(10)
        self.driver.find_element(By.XPATH, "(//div/button/*[local-name()='svg'][@class ='active c-icon'])[2]").click()
        time.sleep(2)
        self.driver.find_element(By.XPATH, "//div[@name = 'special_interest_id']").click()
        self.driver.find_element(By.XPATH, "//li[@id = 'vs5__option-0']").click()
        sinterest = self.driver.find_element(By.XPATH, "//input[@name ='other_special_interest']")
        sinterest.clear()
        sinterest.send_keys("Dental surgery")
        time.sleep(3)
        self.driver.find_element(By.XPATH,"//div[@class ='justify-content-end']/button['btn btn-primary small mr-1']").click()
        self.driver.find_element(By.XPATH, "//button[@class ='btn mr-2 btn-primary small']").click()
        date = self.driver.find_element(By.XPATH, "//label[@name ='lbl_issue_date']")
        self.driver.execute_script("arguments[0].scrollIntoView();", date)
        self.driver.find_element(By.XPATH, "//div[@name ='license_country_id']").click()
        # date = self.driver.find_element(By.XPATH, "//label[@name ='lbl_issue_date']")
        # self.driver.execute_script("arguments[0].scrollIntoView();", date)
        self.driver.find_element(By.XPATH, "//li[@id = 'vs16__option-1']").click()
        self.driver.find_element(By.XPATH, "//div[@name ='license__issue_authority_id']").click()
        self.driver.find_element(By.XPATH, "//li[@id = 'vs17__option-0']").click()
        self.driver.find_element(By.XPATH, "//div[@name ='level_id']").click()
        self.driver.find_element(By.XPATH, "//li[@id= 'vs18__option-3']").click()
        Lno = self.driver.find_element(By.XPATH, "//input[@name ='license_number']")
        Lno.clear()
        Lno.send_keys("56789")
        self.driver.find_element(By.XPATH, "//div[@name ='date-dropdown-month-License_issue_date']").click()
        self.driver.find_element(By.XPATH, "//li[@id = 'vs19__option-9']").click()
        self.driver.find_element(By.XPATH, "//div[@name ='date-dropdown-year-License_issue_date']").click()
        self.driver.find_element(By.XPATH, "//li[@id = 'vs20__option-20']").click()
        self.driver.find_element(By.XPATH, "//input[@id ='local_license-option-true']").click()
        self.driver.find_element(By.XPATH, "//input[@id ='specialist_registration-option-true']").click()
        time.sleep(2)
        save = self.driver.find_element(By.XPATH, "//div/div/button[@class ='btn mr-2 btn-primary small']")
        self.driver.execute_script("arguments[0].click();", save)
        time.sleep(2)
        self.driver.find_element(By.XPATH, "//div/button/*[local-name()='svg'][@class='c-icon']").click()
        Next = self.driver.find_element(By.XPATH, "//button[@name ='next_page']")
        self.driver.execute_script("arguments[0].click();", Next)
        time.sleep(3)
        self.driver.find_element(By.XPATH, "(//div[@class ='col-md-4']/div/button[@class ='btn mr-2 btn-primary small'])[1]").click()
        self.driver.find_element(By.XPATH, "//div[@name ='qualification_name']").click()
        self.driver.find_element(By.XPATH, "//li[@id = 'vs21__option-7']").click()
        self.driver.find_element(By.XPATH, "//input[@name ='others_name']").send_keys("nutrition")
        self.driver.find_element(By.XPATH, "//div[@name  ='date-dropdown-month-qual_month_year']").click()
        self.driver.find_element(By.XPATH, "//li[@id= 'vs23__option-10']").click()
        self.driver.find_element(By.XPATH, "//div[@name ='date-dropdown-year-qual_month_year']").click()
        self.driver.find_element(By.XPATH, "//li[@id = 'vs24__option-27']").click()
        time.sleep(2)
        self.driver.find_element(By.XPATH, "(//div/div/button[@class ='btn mr-2 btn-primary small'])[1]").click()
        # self.driver.implicitly_wait(10)
        # self.driver.find_element(By.XPATH, "//div/div/div/button[@class ='hand-icon action-button']/*[local-name()='svg']").click()
        time.sleep(3)
        self.driver.find_element(By.XPATH, " (//div/div/button[@class ='btn mr-2 btn-primary small'])[2]").click()
        self.driver.find_element(By.XPATH, "//div[@name ='languages_spoken']").click()
        self.driver.find_element(By.XPATH, "//li[@id = 'vs25__option-8']").click()
        self.driver.find_element(By.XPATH, "//div[@name ='language_proficiency']").click()
        self.driver.find_element(By.XPATH, "//li[@id = 'vs26__option-2']").click()
        time.sleep(3)
        self.driver.find_element(By.XPATH, "(//button[@class ='btn mr-2 btn-primary small'])[2]").click()
        # self.driver.implicitly_wait(10)
         # self.driver.find_element(By.XPATH, "//button[@class ='hand-icon action-button']").click()
        time.sleep(3)
        Next1 = self.driver.find_element(By.XPATH, "//div/button[@name ='next_page']")
        self.driver.execute_script("arguments[0].click();", Next1)
        time.sleep(3)
        udoc = self.driver.find_element(By.XPATH, "//div/button[@name ='next_page']")
        self.driver.execute_script("arguments[0].click();", udoc)
        time.sleep(3)
        self.driver.find_element(By.XPATH, "//input[@id ='available-option-true']").click()
        ele2 = self.driver.find_element(By.XPATH, "//div[@class ='vue-slider vue-slider-ltr']")
        action.drag_and_drop_by_offset(ele2, 7, 0).perform()
        self.driver.find_element(By.XPATH, "//div[@name ='date-dropdown-month-available_from']").click()
        self.driver.find_element(By.XPATH, "//li[@id = 'vs28__option-3']").click()
        self.driver.find_element(By.XPATH, "//div[@name ='date-dropdown-year-available_from']").click()
        self.driver.find_element(By.XPATH, "//li[@id = 'vs29__option-2']").click()
        self.driver.find_element(By.XPATH, "//div[@name ='preferred_regions']").click()
        self.driver.find_element(By.XPATH, "//li[@id = 'vs30__option-2']").click()
        self.driver.find_element(By.XPATH, "//div[@ name='preferred_country_id']").click()
        self.driver.find_element(By.XPATH, "//li[@id = 'vs31__option-26']").click()
        self.driver.execute_script("arguments[0].setAttribute('value','5')",
                              self.driver.find_element(By.XPATH, "//input[@name ='current_salary']"))
        self.driver.find_element(By.XPATH, "//div[@name ='current_salary_currency_id']").click()
        self.driver.find_element(By.XPATH, "//li[@id = 'vs32__option-1']").click()
        self.driver.execute_script("arguments[0].setAttribute('value','7')",
                              self.driver.find_element(By.XPATH, "//input[@name ='salary_expectation_min']"))
        self.driver.execute_script("arguments[0].setAttribute('value','11')",
                              self.driver.find_element(By.XPATH, "//input[@name ='salary_expectation_max']"))
        self.driver.find_element(By.XPATH, "//div[@name ='salary_expectation_currency_id']").click()
        Currency1 = self.driver.find_elements(By.XPATH, "//ul[@id = 'vs33__listbox']//li[@class ='vs__dropdown-option']")
        self.driver.find_element(By.XPATH, "//div[@name ='job_type']").click()
        self.driver.find_element(By.XPATH, "//li[@id = 'vs34__option-2']").click()
        self.driver.find_element(By.XPATH, "//div[@name ='job_time']").click()
        self.driver.find_element(By.XPATH, "//li[@id = 'vs35__option-2']").click()
        time.sleep(3)

        self.driver.find_element(By.XPATH, "//button[@class ='hand-icon action-button']")
        time.sleep(3)
        self.driver.find_element(By.XPATH, "//button[@class ='hand-icon action-button ml-2']").click()
        time.sleep(2)
        next = self.driver.find_element(By.XPATH, "//button[@name ='next_page']")
        self.driver.execute_script("arguments[0].click();", next)



        time.sleep(3)
        aemail = self.driver.find_element(By.XPATH, "//input[@name ='alternate_email']")
        aemail.clear()
        aemail.send_keys("sundari@gmail.com")
        self.driver.find_element(By.XPATH, "//div[@name ='phone-code-alternate_phone']").click()
        time.sleep(2)
        self.driver.find_element(By.XPATH, "//li[@id = 'vs37__option-2']").click()
        no = self.driver.find_element(By.XPATH, " //input[@name = 'phone-number-alternate_phone']")
        no.clear()
        no.send_keys("8976045623")
        self.driver.find_element(By.XPATH, "//div[@name='phone-code-whatsapp']").click()

        self.driver.find_element(By.XPATH, "//li[@id ='vs38__option-2']").click()
        no = self.driver.find_element(By.XPATH, " //input[@name='phone-number-whatsapp']")
        no.clear()
        no.send_keys("789056455")
        linked = self.driver.find_element(By.XPATH, "//input[@name ='linkedin_address']")
        linked.clear()
        linked.send_keys("alagusundari")
        skype = self.driver.find_element(By.XPATH, "//input[@name ='skype_id']")
        skype.clear()
        skype.send_keys("sundari21")
        a1 = self.driver.find_element(By.XPATH, "//input[@name='personal_website']")
        a1.clear()
        a1.send_keys("sund.sundari21@gmail.com")
        time.sleep(3)
        self.driver.find_element(By.XPATH, "//button[@class ='hand-icon action-button']").click()
        time.sleep(3)
        self.driver.find_element(By.XPATH, " (//button[normalize-space()='Next'])[1]").click()




        time.sleep(3)

        name = self.driver.find_element(By.XPATH, "//div[@class ='text-input']/input[@name ='known_as']")
        name.clear()
        name.send_keys("Arun")

        passport = self.driver.find_element(By.XPATH, "//input[@name ='passport_number']")
        passport.clear()
        passport.send_keys("45678993455")
        place = self.driver.find_element(By.XPATH, "//label[@name='lbl_birthplace']")
        self.driver.execute_script("arguments[0].scrollIntoView();", place)
        self.driver.find_element(By.XPATH, "//div[@name='birth_place']").click()
        self.driver.find_element(By.XPATH, "//li[@id = 'vs47__option-2']").click()
        self.driver.find_element(By.XPATH, "//input[@id='marital_status-option-Married']").click()
        self.driver.find_element(By.XPATH, "//input[@id='marital_partner_seeking_job-option-true']").click()
        self.driver.find_element(By.XPATH, "//input[@id='spouse_registered-option-true']").click()
        wife = self.driver.find_element(By.XPATH, "//input[@name ='name_of_spouse']")
        wife.clear()
        wife.send_keys("sundari")
        wemail = self.driver.find_element(By.XPATH, "//input[@name ='spouse_email']")
        wemail.clear()
        wemail.send_keys("arun@gmail.com")
        relocate = self.driver.find_element(By.XPATH, "//div/label[@name ='lbl_relocate_family']")
        self.driver.execute_script("arguments[0].scrollIntoView();", relocate)
        ele4 = self.driver.find_element(By.XPATH, "//div[@name ='dependents']").click()
        action.drag_and_drop_by_offset(ele4, 8, 0).perform()
        self.driver.find_element(By.XPATH, "//input[@id ='relocate_family-option-true']").click()
        time.sleep(3)
        self.driver.find_element(By.XPATH,
                            "//div[@class ='d-flex justify-content-end']/button/*[local-name()='svg'][@class ='active c-icon']").click()
        time.sleep(3)
        self.driver.find_element(By.XPATH,"//div/button[@class ='hand-icon action-button mr-3']").click()
        time.sleep(3)
        pnext = self.driver.find_element(By.XPATH, "//div/div/button[contains(text(),'Next')]")
        self.driver.execute_script("arguments[0].click();", pnext)




        time.sleep(3)
        self.driver.find_element(By.XPATH, "//input[@name='subscription_preferences']").click()
        self.driver.find_element(By.XPATH, "//div[@name ='display_data_id']").click()
        self.driver.find_element(By.XPATH, "//li[@id = 'vs48__option-4']").click()
        time.sleep(2)
        stars = self.driver.find_element(By.XPATH,"//div/div/label/input[@class='star-rating star-rating__checkbox'][@value='3.5']")
        action.move_to_element(stars).click().perform()
        opnion = self.driver.find_element(By.XPATH, "//div/div/input[@name='do_better']")
        opnion.clear()
        opnion.send_keys("Nothing")
        self.driver.find_element(By.XPATH, "//input[@id='applied_to_other_agencies-option-true']").click()
        self.driver.find_element(By.XPATH, "(//span[@class ='c-switch-slider'])[5]").click()
        self.driver.find_element(By.XPATH, "//div/label/input[@id ='delete_my_account-option-[object Object]']").click()
        time.sleep(3)
        self.driver.find_element(By.XPATH, "//button[@class ='hand-icon action-button']/*[local-name()='svg']").click()
        time.sleep(3)
        self.driver.find_element(By.XPATH,"//div/button[@class ='hand-icon action-button']/*[local-name() ='svg']").click()
        time.sleep(3)
        done = self.driver.find_element(By.XPATH, "//div/div/button[@name ='done_page']")
        self.driver.execute_script("arguments[0].click();", done)


class TestClass3(BaseClass):
    def test_demo3(self):
        time.sleep(3)
        username = "admin@ohragency.stage"
        password = "OhR@1234"
        action = ActionChains(self.driver)
        time.sleep(3)
        self.driver.find_element(By.NAME, 'login-email').send_keys(username)
        self.driver.find_element(By.NAME, 'login-password').send_keys(password)
        self.driver.find_element(By.XPATH, "//button[@name ='login-submit']").click()

        time.sleep(4)
        self.driver.find_element(By.XPATH, "//button[@class ='btn px-4 btn-outline-primary']").click()
        ele = self.driver.find_element(By.XPATH, "//span[@class ='ml-2 header-nav'][contains(text() ,'Jobs')]")
        action.move_to_element(ele).perform()
        self.driver.find_element(By.XPATH, "//em[@class ='fas fa-laptop-medical mr-2']").click()

        time.sleep(5)
        self.driver.find_element(By.XPATH, "//div[@name ='organisation']").click()
        self.driver.find_element(By.XPATH, "//li[@id ='vs3__option-1']").click()
        self.driver.find_element(By.NAME, "location_id").click()
        self.driver.find_element(By.XPATH, "//li[@id ='vs4__option-0']").click()
        self.driver.find_element(By.XPATH, "//input[@name ='job_title']").send_keys("sun_testcase")
        self.driver.find_element(By.XPATH, "//div[@name ='candidateType']").click()
        self.driver.find_element(By.XPATH, "//li[@id ='vs5__option-1']").click()
        self.driver.find_element(By.NAME, "level").click()
        self.driver.find_element(By.XPATH, "//li[@id ='vs6__option-1']").click()
        time.sleep(3)
        self.driver.find_element(By.XPATH, "//div[@name ='speciality']").click()
        self.driver.find_element(By.XPATH, "//li[@id ='vs7__option-1']").click()
        scroll1 = self.driver.find_element(By.XPATH, "//label[contains(text(),'Number of years in Speciality')]")
        self.driver.execute_script("arguments[0].scrollIntoView();", scroll1)
        time.sleep(2)
        ele = self.driver.find_element(By.XPATH, "//div[@name ='experience_in_years']")
        action.drag_and_drop_by_offset(ele, 60, 0).perform()
        # self.driver.find_element(By.XPATH, "//div[@name ='other_areas_of_expertise_ids']").click()
        # time.sleep(3)
        # self.driver.find_element(By.XPATH, "//li[@id ='vs18__option-8']").click()
        self.driver.find_element(By.XPATH, "//div[@name ='special_interest_ids']").click()
        self.driver.find_element(By.XPATH, "//li[@id ='vs8__option-5']").click()

        self.driver.find_element(By.XPATH, "//div[@name ='job_contact_recruiters']").click()
        self.driver.find_element(By.XPATH, "//li[@id ='vs9__option-3']").click()
        self.driver.find_element(By.XPATH, "//div[@name ='customer_organisation_contact_id']").click()
        self.driver.find_element(By.XPATH, "//li[@id ='vs10__option-1']").click()
        self.driver.find_element(By.XPATH, "//div[@name ='candidate_reviewer']").click()
        self.driver.find_element(By.XPATH, "//li[@id = 'vs11__option-0']").click()
        self.driver.find_element(By.XPATH, "//div[@name ='job_approval']").click()
        time.sleep(3)
        job = self.driver.find_element(By.XPATH,"//li[@class ='vs__dropdown-option']")
        self.driver.execute_script("arguments[0].click();", job)

        self.driver.find_element(By.XPATH, "//div[@name ='candidate_interviewer']").click()
        self.driver.find_element(By.XPATH, "//li[@id ='vs12__option-2']").click()


        scroll = self.driver.find_element(By.XPATH, "//label[contains(text(),'Local License or Eligibility')]")
        self.driver.execute_script("arguments[0].scrollIntoView();", scroll)
        ele1 = self.driver.find_element(By.XPATH, "//div[@name ='min_yrs_of_exp']")
        action.drag_and_drop_by_offset(ele1, 60, 0).perform()

        self.driver.find_element(By.XPATH, "//input[@id ='regional_license-option-required']").click()
        self.driver.find_element(By.XPATH, "//input[@id ='gender_id-option-2']").click()

        ele2 = self.driver.find_element(By.XPATH, "//div[@name ='maximum_age']")
        action.drag_and_drop_by_offset(ele2, 60, 0).perform()
        self.driver.execute_script("arguments[0].setAttribute('value','7')",
                                   self.driver.find_element(By.XPATH, "//input[@name ='allocated_budget']"))
        self.driver.find_element(By.XPATH, "//div[@name ='allocated_budget_currency_id']").click()
        self.driver.find_element(By.XPATH, "//li[@id ='vs17__option-1']").click()
        self.driver.execute_script("arguments[0].setAttribute('value','6')",
                                   self.driver.find_element(By.XPATH, "//input[@name ='positions_available']"))
        # self.driver.find_element(By.XPATH,"//button[@name ='draft']").click()
        time.sleep(4)
        self.driver.find_element(By.XPATH, "//div/button[@name ='next']").click()

        time.sleep(3)
        self.driver.find_element(By.XPATH, "//input[@name ='target_salary_text']").send_keys("50000")
        self.driver.find_element(By.XPATH, "//div[@name='target_salary_currency_id']").click()
        self.driver.find_element(By.XPATH, "//li[@id ='vs20__option-122']").click()
        self.driver.find_element(By.XPATH, "//input[@name ='salary_min_text']").send_keys("60000")
        self.driver.find_element(By.XPATH, "//input[@name ='salary_max_text']").send_keys("100000")
        self.driver.find_element(By.XPATH, "//div[@name ='salary_currency_id']").click()
        self.driver.find_element(By.XPATH, "//li[@id ='vs21__option-122']").click()
        self.driver.find_element(By.XPATH, "//input[@id ='salary-option-[object Object]']").click()

        self.driver.find_element(By.XPATH, "//input[@id ='full_time-option-yes']").click()
        self.driver.find_element(By.XPATH, "//input[@id ='part_time-option-no']").click()
        self.driver.find_element(By.XPATH, "//input[@id ='permanent_work-option-true']").click()
        self.driver.find_element(By.XPATH, "//input[@id ='temporary_work-option-[object Object]']").click()
        self.driver.find_element(By.XPATH, "//input[@id ='visiting_locum-option-[object Object]']").click()
        self.driver.execute_script("arguments[0].setAttribute('value','5')",
                                   self.driver.find_element(By.XPATH, "//input[@name ='working_hours']"))
        self.driver.execute_script("arguments[0].setAttribute('value','4')",
                                   self.driver.find_element(By.XPATH, "//input[@name ='working_days']"))
        self.driver.find_element(By.XPATH, "//div[@name ='facility_type']").click()
        self.driver.find_element(By.XPATH, "//li[@id ='vs22__option-0']").click()
        self.driver.find_element(By.XPATH, "//input[@name ='type_of_contract']").send_keys("permanent")
        self.driver.find_element(By.XPATH, "//textarea[@name ='additional_info']").send_keys("No comments")
        self.driver.find_element(By.XPATH, "//textarea[@name ='comments']").send_keys("No comments")
        next1 = self.driver.find_element(By.XPATH, "//button[@name ='next_page']")
        self.driver.execute_script("arguments[0].click();", next1)

        time.sleep(3)
        self.driver.find_element(By.XPATH,
                                 "(//table[@class ='table table-striped table-hover border-bottom mb-0 desktop-view']/thead/tr/td)[1]").click()
        next2 = self.driver.find_element(By.XPATH, "//button[@name ='next_page']")
        self.driver.execute_script("arguments[0].click();", next2)

        time.sleep(3)
        self.driver.find_element(By.XPATH, "//table[@class ='table table-hover']/thead/tr/th[2]/div/a").click()
        s1 = self.driver.find_element(By.XPATH, "//h6[contains(text(),'Job Heading')]")
        self.driver.execute_script("arguments[0].scrollIntoView();", s1)
        time.sleep(2)
        self.driver.find_element(By.XPATH, "//input[@name = 'Organisation_Description']").click()
        self.driver.find_element(By.XPATH, "(//input[@name = 'Job_Description'])[3]").click()
        s2 = self.driver.find_element(By.XPATH, "(//h6[contains(text(),'Registered Nurse')])[2]")
        self.driver.execute_script("arguments[0].scrollIntoView();", s2)
        self.driver.find_element(By.XPATH, "(//input[@name = 'Qualifications_Required'])[4]").click()
        time.sleep(2)
        self.driver.find_element(By.XPATH, "//input[@name = 'Essential_Requirements']")
        s3 = self.driver.find_element(By.XPATH, "//h6[contains(text(),'Preferred Requirements')]")
        self.driver.execute_script("arguments[0].scrollIntoView();", s3)
        self.driver.find_element(By.XPATH, "//input[@name = 'Preferred_Requirements']").click()
        self.driver.find_element(By.XPATH, "//div[@class ='row justify-content-between ml-0 mr-0 hover-gray']").click()
        add = self.driver.find_element(By.XPATH, "//div[@class ='quillWrapper advert-section']")
        action.click(add).send_keys("additional information").perform()

        nxt = self.driver.find_element(By.XPATH, "//button[@name ='next_page']")
        self.driver.execute_script("arguments[0].click();", nxt)

        time.sleep(3)
        self.driver.find_element(By.NAME, "document_type").click()
        self.driver.find_element(By.XPATH, "//li[@id ='vs23__option-0']").click()
        choose = self.driver.find_element(By.XPATH, "//div/div/input[@id ='document-upload']")
        action.move_to_element(choose).click().perform()
        time.sleep(3)
        autoit.control_focus("Open", "Edit1")
        time.sleep(3)
        autoit.control_set_text("Open", "Edit1","C:\\Users\\ALAGU SUNDARI\\OneDrive\\Desktop\\sundari.docx")
        time.sleep(3)
        autoit.control_click("Open", "Button1")

        self.driver.find_element(By.XPATH, "//div[@name ='expiry_review_date']").click()
        time.sleep(3)
        self.driver.find_element(By.XPATH,
                                 "//table[@class ='mx-table mx-table-date']/tbody/tr[3]/td[@title='2023-03-12']").click()
        fnext = self.driver.find_element(By.XPATH, "//button[contains(text(),'Send For Approval')]")
        self.driver.execute_script("arguments[0].click();", fnext)
        time.sleep(2)
        self.driver.find_element(By.XPATH, "(//input[@id ='publish_request_is_urgent-option-[object Object]'])[1]").click()
        self.driver.find_element(By.XPATH, "//div[@name ='customComments']").click()
        self.driver.find_element(By.XPATH, "//li[@id ='vs25__option-0']").click()
        self.driver.find_element(By.XPATH, "//button[@name ='publish_page']").click()
        time.sleep(3)

